alter table Friendship drop constraint FKc5lmnwd99v09lcolljj3y2ube
alter table Friendship drop constraint FK5i9k3ng3s6477p7tsu0p8a2bf
drop table if exists Friendship cascade
drop table if exists UserNode cascade
alter table Friendship drop constraint FKc5lmnwd99v09lcolljj3y2ube
alter table Friendship drop constraint FK5i9k3ng3s6477p7tsu0p8a2bf
drop table if exists Friendship cascade
drop table if exists UserNode cascade
alter table Friendship drop constraint FKc5lmnwd99v09lcolljj3y2ube
alter table Friendship drop constraint FK5i9k3ng3s6477p7tsu0p8a2bf
drop table if exists Friendship cascade
drop table if exists UserNode cascade
alter table Friendship drop constraint FKc5lmnwd99v09lcolljj3y2ube
alter table Friendship drop constraint FK5i9k3ng3s6477p7tsu0p8a2bf
drop table if exists Friendship cascade
drop table if exists UserNode cascade
alter table Friendship drop constraint FKc5lmnwd99v09lcolljj3y2ube
alter table Friendship drop constraint FK5i9k3ng3s6477p7tsu0p8a2bf
drop table if exists Friendship cascade
drop table if exists UserNode cascade
alter table Friendship drop constraint FKc5lmnwd99v09lcolljj3y2ube
alter table Friendship drop constraint FK5i9k3ng3s6477p7tsu0p8a2bf
drop table if exists Friendship cascade
drop table if exists UserNode cascade
alter table Friendship drop constraint FKc5lmnwd99v09lcolljj3y2ube
alter table Friendship drop constraint FK5i9k3ng3s6477p7tsu0p8a2bf
drop table if exists Friendship cascade
drop table if exists UserNode cascade
alter table Friendship drop constraint FKc5lmnwd99v09lcolljj3y2ube
alter table Friendship drop constraint FK5i9k3ng3s6477p7tsu0p8a2bf
drop table if exists Friendship cascade
drop table if exists UserNode cascade
alter table Friendship drop constraint FKc5lmnwd99v09lcolljj3y2ube
alter table Friendship drop constraint FK5i9k3ng3s6477p7tsu0p8a2bf
drop table if exists Friendship cascade
drop table if exists UserNode cascade
alter table Friendship drop constraint FKc5lmnwd99v09lcolljj3y2ube
alter table Friendship drop constraint FK5i9k3ng3s6477p7tsu0p8a2bf
drop table if exists Friendship cascade
drop table if exists UserNode cascade
alter table Friendship drop constraint FKc5lmnwd99v09lcolljj3y2ube
alter table Friendship drop constraint FK5i9k3ng3s6477p7tsu0p8a2bf
drop table if exists Friendship cascade
drop table if exists UserNode cascade
alter table Friendship drop constraint FKc5lmnwd99v09lcolljj3y2ube
alter table Friendship drop constraint FK5i9k3ng3s6477p7tsu0p8a2bf
drop table if exists Friendship cascade
drop table if exists UserNode cascade
alter table Friendship drop constraint FKc5lmnwd99v09lcolljj3y2ube
alter table Friendship drop constraint FK5i9k3ng3s6477p7tsu0p8a2bf
drop table if exists Friendship cascade
drop table if exists UserNode cascade
alter table Friendship drop constraint FKc5lmnwd99v09lcolljj3y2ube
alter table Friendship drop constraint FK5i9k3ng3s6477p7tsu0p8a2bf
drop table if exists Friendship cascade
drop table if exists UserNode cascade
